import {chromium} from 'playwright';
import {createServer} from 'node:http';
import {readFile} from 'node:fs/promises';
import {join,resolve,sep} from 'node:path';
import assert from 'node:assert/strict';
const root=resolve(import.meta.dirname,'..');
const mime={'.html':'text/html','.css':'text/css','.mjs':'text/javascript','.png':'image/png'};
const server=createServer(async(req,res)=>{try{const pathname=decodeURIComponent(req.url.split('?')[0]);const path=resolve(root,'.'+pathname);if(path!==root&&!path.startsWith(root+sep))throw Error('path');const file=pathname.endsWith('/')?join(path,'index.html'):path;const data=await readFile(file);res.writeHead(200,{'Content-Type':mime[file.slice(file.lastIndexOf('.'))]||'text/plain'});res.end(data)}catch{res.writeHead(404);res.end()}});
await new Promise(resolve=>server.listen(0,'0.0.0.0',resolve));
const base=`http://127.0.0.1:${server.address().port}/the-shop/`;
const browser=await chromium.launch({headless:true,args:['--no-sandbox'],...(process.env.SHOP_CHROME ? {executablePath:process.env.SHOP_CHROME} : {})});
try{
  for(const viewport of [{width:1440,height:900},{width:375,height:812}]){
    const context=await browser.newContext({viewport,acceptDownloads:true});const page=await context.newPage();
    const legacy=JSON.stringify({schema:'system-by-dave.gear-prep.v1',meta:{showName:'Test show'},items:[{id:'legacy-a',item:'Camera kit',qty:'3',caseId:'CAM-1',owner:'Video',status:'issue',notes:'Keep batteries'}]});
    await page.addInitScript(bytes=>localStorage.setItem('gear-prep.v1',bytes),legacy);
    await page.goto(base);
    await page.getByRole('button',{name:'Import source'}).click();
    await page.getByRole('button',{name:'Preview saved source'}).click();
    assert.match(await page.locator('#importPreview').innerText(),/1 rows ready/);
    assert.match(await page.locator('#importPreview').innerText(),/Requested 3 · Packed not counted/);
    await page.getByRole('button',{name:'Close import'}).click();
    assert.equal(await page.getByRole('button',{name:/Camera kit/}).count(),0);
    await page.getByRole('button',{name:'Import source'}).click();
    await page.locator('#importFile').setInputFiles({name:'bad-count.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({schema:'system-by-dave.gear-prep.v1',items:[{id:'bad-count',item:'Bad count',qty:'1.5'}]}))});
    await page.waitForFunction(()=>document.getElementById('importPreview').textContent.includes('quantity'));
    assert.equal(await page.getByRole('button',{name:'Add previewed rows'}).isDisabled(),true);
    await page.getByRole('button',{name:'Close import'}).click();
    await page.getByRole('button',{name:'Import source'}).click();
    await page.getByRole('button',{name:'Preview saved source'}).click();
    await page.evaluate(bytes=>localStorage.setItem('gear-prep.v1',bytes.replace('Keep batteries','Updated elsewhere')),legacy);
    await page.getByRole('button',{name:'Add previewed rows'}).click();
    assert.match(await page.locator('#importPreview').innerText(),/changed after preview/);
    assert.equal(await page.getByRole('button',{name:/Camera kit/}).count(),0);
    await page.evaluate(bytes=>localStorage.setItem('gear-prep.v1',bytes),legacy);
    await page.getByRole('button',{name:'Preview saved source'}).click();
    await page.getByRole('button',{name:'Add previewed rows'}).click();
    await page.getByRole('button',{name:/Camera kit/}).click();
    assert.equal(await page.locator('[name=requestedQty]').inputValue(),'3');
    assert.equal(await page.locator('[name=packedQty]').inputValue(),'');
    await page.locator('[name=packedQty]').fill('4');
    await page.getByRole('button',{name:'Apply changes'}).click();
    assert.match(await page.locator('#footerMessage').innerText(),/cannot exceed requested/);
    assert.match(await page.locator('#countHelp').innerText(),/cannot exceed requested/);
    assert.equal(await page.locator('#countHelp').getAttribute('role'),'alert');
    assert.equal(await page.locator('[name=packedQty]').getAttribute('aria-invalid'),'true');
    const errorInView=await page.locator('#countHelp').evaluate(el=>{const error=el.getBoundingClientRect(),form=el.closest('form').getBoundingClientRect();return error.top>=form.top&&error.bottom<=form.bottom&&error.top>=0&&error.bottom<=innerHeight});
    assert.equal(errorInView,true);
    assert.match(await page.getByRole('button',{name:/Camera kit/}).innerText(),/Packed not counted/);
    await page.locator('[name=packedQty]').fill('1');
    assert.match(await page.locator('#countHelp').innerText(),/Blank means unknown/);
    assert.equal(await page.locator('[name=packedQty]').getAttribute('aria-invalid'),'false');
    await page.locator('[name=owner]').fill('Lead video');
    await page.getByRole('button',{name:'Apply changes'}).click();
    await page.getByRole('button',{name:'Save plan'}).click();
    await page.reload();
    assert.match(await page.getByRole('button',{name:/Camera kit/}).innerText(),/Lead video/);
    assert.match(await page.getByRole('button',{name:/Camera kit/}).innerText(),/Packed 1 \/ 3 \(partial\)/);
    assert.equal(await page.evaluate(()=>localStorage.getItem('gear-prep.v1')),legacy);
    const exportPromise=page.waitForEvent('download');
    await page.getByRole('button',{name:'Export JSON'}).click();
    const exportDownload=await exportPromise;
    const exported=JSON.parse(await readFile(await exportDownload.path(),'utf8'));
    assert.equal(exported.items[0].requestedQty,3);
    assert.equal(exported.items[0].packedQty,1);
    assert.equal(exported.items[0].original.qty,'3');
    await page.getByRole('button',{name:/Camera kit/}).click();
    await page.locator('[name=title]').fill('   ');
    await page.locator('[name=owner]').fill('Should not apply');
    await page.getByRole('button',{name:'Apply changes'}).click();
    assert.equal(await page.locator('#detailTitle').innerText(),'Camera kit');
    await page.reload();
    assert.match(await page.getByRole('button',{name:/Camera kit/}).innerText(),/Lead video/);
    await page.getByRole('button',{name:'Import source'}).click();
    await page.locator('#importFile').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{bad')});
    assert.equal(await page.getByRole('button',{name:'Add previewed rows'}).isDisabled(),true);
    await page.getByRole('button',{name:'Close import'}).click();
    assert.equal(await page.getByRole('button',{name:/Camera kit/}).count(),1);
    await page.getByRole('button',{name:'Import source'}).click();
    await page.getByRole('button',{name:'Preview saved source'}).click();
    assert.match(await page.locator('#importPreview').innerText(),/already in this Shop plan/);
    assert.equal(await page.getByRole('button',{name:'Add previewed rows'}).isDisabled(),true);
    await page.getByRole('button',{name:'Close import'}).click();
    await page.getByRole('button',{name:'Import source'}).click();
    await page.locator('#sourceKind').selectOption('shop-backup');
    const backup=await page.evaluate(()=>localStorage.getItem('sbd.shop.v1'));
    await page.locator('#importFile').setInputFiles({name:'shop.json',mimeType:'application/json',buffer:Buffer.from(backup)});
    await page.waitForFunction(()=>document.getElementById('importPreview').textContent.includes('Shop rows ready to restore'));
    assert.match(await page.locator('#importPreview').innerText(),/Shop rows ready to restore/);
    await page.getByRole('button',{name:'Close import'}).click();
    assert.equal(await page.evaluate(()=>localStorage.getItem('sbd.shop.v1')),backup);
    const firstTheme=await page.locator('html').getAttribute('data-av-theme');
    await page.getByRole('button',{name:firstTheme==='dark'?'Light mode':'Dark mode'}).click();
    const nextTheme=firstTheme==='dark'?'light':'dark';
    assert.equal(await page.locator('html').getAttribute('data-av-theme'),nextTheme);
    assert.equal(await page.evaluate(()=>localStorage.getItem('av-theme-mode.v1')),nextTheme);
    await page.reload();
    assert.equal(await page.locator('html').getAttribute('data-av-theme'),nextTheme);
    await page.screenshot({path:join(process.env.SHOP_CAPTURE_DIR||'/work',`the-shop-light-${viewport.width}.png`),fullPage:true});
    await page.getByRole('button',{name:nextTheme==='dark'?'Light mode':'Dark mode'}).click();
    await page.locator('.skip').focus();
    await page.keyboard.press('Enter');
    assert.equal(await page.evaluate(()=>document.activeElement.id),'worklist');
    const overflow=await page.evaluate(()=>({vertical:document.documentElement.scrollHeight>document.documentElement.clientHeight,horizontal:document.documentElement.scrollWidth>document.documentElement.clientWidth}));
    assert.deepEqual(overflow,{vertical:false,horizontal:false});
    const paint=await page.evaluate(()=>{const swatch=document.createElement('span');swatch.style.color='var(--av-surface-2)';document.body.append(swatch);const expected=getComputedStyle(swatch).color;swatch.remove();return {expected,row:getComputedStyle(document.querySelector('.row')).backgroundColor,button:getComputedStyle(document.getElementById('importBtn')).backgroundColor}});
    assert.equal(paint.row,paint.expected,'row background changes with the theme without low-contrast transition');
    assert.equal(paint.button,paint.expected,'button background changes with the theme without low-contrast transition');
    await page.screenshot({path:join(process.env.SHOP_CAPTURE_DIR||'/work',`the-shop-${viewport.width}.png`),fullPage:true});
    await page.getByRole('button',{name:/Camera kit/}).click();
    await page.locator('[name=packedQty]').scrollIntoViewIfNeeded();
    assert.equal(await page.locator('[name=packedQty]').inputValue(),'1');
    await page.screenshot({path:join(process.env.SHOP_CAPTURE_DIR||'/work',`the-shop-detail-${viewport.width}.png`),fullPage:true});
    await page.getByRole('button',{name:'Apply changes'}).scrollIntoViewIfNeeded();
    assert.equal(await page.getByRole('button',{name:'Apply changes'}).isVisible(),true);
    if(viewport.width===1440){
      for(const size of [{width:844,height:390},{width:320,height:256},{width:3840,height:1080}]){
        await page.setViewportSize(size);
        const dimensions=await page.evaluate(()=>({vertical:document.documentElement.scrollHeight>document.documentElement.clientHeight,horizontal:document.documentElement.scrollWidth>document.documentElement.clientWidth}));
        assert.deepEqual(dimensions,{vertical:false,horizontal:false},`root overflow at ${size.width}x${size.height}`);
        await page.locator('[name=packedQty]').scrollIntoViewIfNeeded();
        assert.equal(await page.locator('[name=packedQty]').isVisible(),true);
      }
    }
    await page.emulateMedia({media:'print'});
    const print=await page.evaluate(()=>({root:getComputedStyle(document.documentElement).overflowY,rows:getComputedStyle(document.getElementById('rows')).overflowY,form:getComputedStyle(document.getElementById('itemForm')).overflowY}));
    assert.deepEqual(print,{root:'visible',rows:'visible',form:'visible'});
    await page.emulateMedia({media:'screen'});
    await context.close();
    const recoveryContext=await browser.newContext({viewport,acceptDownloads:true});
    const recoveryPage=await recoveryContext.newPage();
    const damaged='{this is unreadable';
    await recoveryPage.goto(base);
    await recoveryPage.evaluate(value=>localStorage.setItem('sbd.shop.v1',value),damaged);
    await recoveryPage.reload();
    await recoveryPage.getByRole('button',{name:'Save plan'}).click();
    assert.equal(await recoveryPage.evaluate(()=>localStorage.getItem('sbd.shop.v1')),damaged);
    const downloadPromise=recoveryPage.waitForEvent('download');
    await recoveryPage.getByRole('button',{name:'Export JSON'}).click();
    const download=await downloadPromise;
    assert.equal(await readFile(await download.path(),'utf8'),damaged);
    await recoveryPage.getByRole('button',{name:'Import source'}).click();
    await recoveryPage.locator('#sourceKind').selectOption('shop-backup');
    await recoveryPage.locator('#importFile').setInputFiles({name:'recovery.json',mimeType:'application/json',buffer:Buffer.from(backup)});
    await recoveryPage.waitForFunction(()=>document.getElementById('importPreview').textContent.includes('Shop rows ready to restore'));
    recoveryPage.once('dialog',dialog=>dialog.accept());
    await recoveryPage.getByRole('button',{name:'Add previewed rows'}).click();
    assert.equal(await recoveryPage.evaluate(()=>localStorage.getItem('sbd.shop.v1')),damaged);
    await recoveryPage.evaluate(()=>{window.originalSetItem=Storage.prototype.setItem;Storage.prototype.setItem=function(key,value){if(key.startsWith('sbd.shop.recovery.'))throw new Error('fixture write failure');return window.originalSetItem.call(this,key,value)}});
    await recoveryPage.getByRole('button',{name:'Save plan'}).click();
    assert.equal(await recoveryPage.evaluate(()=>localStorage.getItem('sbd.shop.v1')),damaged);
    assert.match(await recoveryPage.locator('#footerMessage').innerText(),/fixture write failure/);
    await recoveryPage.evaluate(()=>{Storage.prototype.setItem=window.originalSetItem});
    await recoveryPage.getByRole('button',{name:'Save plan'}).click();
    const recovered=await recoveryPage.evaluate(()=>({plan:localStorage.getItem('sbd.shop.v1'),backups:Object.entries(localStorage).filter(([key])=>key.startsWith('sbd.shop.recovery.'))}));
    assert.equal(JSON.parse(recovered.plan).items.length,1);
    assert.equal(recovered.backups.length,1);
    assert.equal(recovered.backups[0][1],damaged);
    assert.equal(JSON.parse(recovered.plan).items[0].packedQty,1);
    await recoveryPage.reload();
    assert.equal(await recoveryPage.getByRole('button',{name:/Camera kit/}).count(),1);
    const oldBackup=JSON.stringify({schema:'system-by-dave.shop.v1',name:'Old Shop',items:[{id:'old-rack',title:'Old rack',phase:'pack',status:'ready'}]});
    await recoveryPage.getByRole('button',{name:'Import source'}).click();
    await recoveryPage.locator('#sourceKind').selectOption('shop-backup');
    await recoveryPage.locator('#importFile').setInputFiles({name:'old-shop.json',mimeType:'application/json',buffer:Buffer.from(oldBackup)});
    await recoveryPage.waitForFunction(()=>document.getElementById('importPreview').textContent.includes('Shop rows ready to restore'));
    recoveryPage.once('dialog',dialog=>dialog.accept());
    await recoveryPage.getByRole('button',{name:'Add previewed rows'}).click();
    await recoveryPage.getByRole('button',{name:'Save plan'}).click();
    await recoveryPage.reload();
    assert.match(await recoveryPage.getByRole('button',{name:/Old rack/}).innerText(),/Requested unknown · Packed not counted/);
    const oldRestored=JSON.parse(await recoveryPage.evaluate(()=>localStorage.getItem('sbd.shop.v1')));
    assert.equal(oldRestored.items[0].requestedQty,null);
    assert.equal(oldRestored.items[0].packedQty,null);
    await recoveryContext.close();
  }
  console.log('The Shop browser probe passed: quantity preview/partial pack, stale/repeated/malformed rejection, old backup, save/reload/export/restore, source parity, damaged-save recovery, themes, keyboard, five viewport sizes and print overflow.');
}finally{await browser.close();server.close()}
