import {KEY,SCHEMA,SOURCES,PHASES,STATUSES,emptyPlan,validatePlan,stageLegacy,countPair,assertFreshSourceRows} from './model.mjs';
const $ = id => document.getElementById(id);
const storage = window.localStorage;
let plan = emptyPlan(), savedBytes = null, blocked = false, dirty = false, selected = null, activePhase = 'all', pending = null, pendingPlan = null, pendingOrigin = null, recoveryKey = null, recoveryAuthorized = false;
const names = Object.fromEntries(Object.entries(SOURCES).map(([key,value])=>[key,value.label]));
const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function message(value,error=false){ $('footerMessage').textContent=value; $('saveState').textContent=error?'Needs attention':value; $('saveState').style.color=error?'var(--hold)':''; }
function load(){try{savedBytes=storage.getItem(KEY);if(savedBytes)plan=validatePlan(JSON.parse(savedBytes));}catch(error){blocked=true;message(`Saved plan was not opened: ${error.message}`,true);} $('planName').value=plan.name;render();}
function changed(){dirty=true;message('Unsaved changes');render();}
function counts(){ $('countAll').textContent=plan.items.length;$('allBadge').textContent=plan.items.length;$('countWorking').textContent=plan.items.filter(x=>x.status==='working').length;$('countHold').textContent=plan.items.filter(x=>x.status==='hold'||x.blocker.trim()).length;$('countReady').textContent=plan.items.filter(x=>x.status==='ready').length; }
function quantityLabel(item){const requested=item.requestedQty??'unknown',packed=item.packedQty??'not counted';return `Requested ${requested} · Packed ${packed}${item.requestedQty!==null&&item.packedQty!==null?` / ${item.requestedQty}${item.packedQty<item.requestedQty?' (partial)':''}`:''}`;}
const countHelpText=$('countHelp').textContent;
function countError(value=''){const help=$('countHelp');help.textContent=value||countHelpText;help.classList.toggle('error',Boolean(value));if(value)help.setAttribute('role','alert');else help.removeAttribute('role');$('itemForm').elements.packedQty.setAttribute('aria-invalid',value?'true':'false');}
function render(){counts();const q=$('search').value.trim().toLowerCase(),status=$('statusFilter').value;const rows=plan.items.filter(x=>(activePhase==='all'||x.phase===activePhase)&&(status==='all'||x.status===status)&&(!q||[x.title,x.caseId,x.department,x.owner,x.location,x.destination,x.blocker].join(' ').toLowerCase().includes(q)));$('phaseKicker').textContent=activePhase==='all'?'ALL PHASES':`${String(PHASES.indexOf(activePhase)+1).padStart(2,'0')} / ${activePhase.toUpperCase()}`;$('phaseTitle').textContent=activePhase==='all'?'Worklist':activePhase[0].toUpperCase()+activePhase.slice(1);document.querySelectorAll('.phase-nav button[data-phase]').forEach(b=>{b.classList.toggle('active',b.dataset.phase===activePhase);b.setAttribute('aria-current',b.dataset.phase===activePhase?'page':'false')});$('rows').innerHTML=rows.length?rows.map(x=>`<button type="button" class="row ${x.id===selected?'selected':''}" data-id="${esc(x.id)}"><span class="phase-pill">${esc(x.phase)}</span><span><strong>${esc(x.title)}</strong><small>${esc([x.caseId,x.owner,x.department].filter(Boolean).join(' · ')||'Unassigned')} ${x.blocker?' · ⚠ '+esc(x.blocker):''}</small><small class="quantity-summary">${esc(quantityLabel(x))}</small></span><span class="status-pill ${esc(x.status)}">${esc(x.status)}</span></button>`).join(''):'<div class="empty">No items in this view. Add an item or import a source plan.</div>';$('rows').querySelectorAll('[data-id]').forEach(button=>button.addEventListener('click',()=>select(button.dataset.id)));renderDetail();}
function renderDetail(){const item=plan.items.find(x=>x.id===selected);$('itemForm').hidden=!item;$('detailTitle').textContent=item?.title||'Choose an item';$('detailSource').textContent=item?.source?`Copied from ${names[item.source.kind]||item.source.kind}${item.source.show?' · '+item.source.show:''}. Original record retained.`:'Select a row to edit ownership, location and readiness.';if(!item)return;for(const key of ['title','caseId','department','owner','location','destination','notes','blocker','phase','status'])$('itemForm').elements[key].value=item[key];for(const key of ['requestedQty','packedQty'])$('itemForm').elements[key].value=item[key]??'';$('detail').classList.add('open');}
function select(id){selected=id;countError();render();if(matchMedia('(max-width:780px)').matches){$('detail').classList.add('open');$('itemForm').elements.title.focus();}}
$('planName').addEventListener('input',event=>{plan.name=event.target.value;dirty=true;message('Unsaved changes');});
document.querySelectorAll('.phase-nav button[data-phase]').forEach(b=>b.addEventListener('click',()=>{activePhase=b.dataset.phase;$('detail').classList.remove('open');render()}));
$('search').addEventListener('input',render);$('statusFilter').addEventListener('change',render);
$('addBtn').addEventListener('click',()=>{if(blocked&&!recoveryAuthorized)return message('Saved plan needs recovery before editing. Export or repair it first.',true);const item={id:crypto.randomUUID(),title:'New shop item',caseId:'',department:'',owner:'',location:'',destination:'',notes:'',blocker:'',phase:activePhase==='all'?'prep':activePhase,status:'queued',requestedQty:null,packedQty:null,source:null,original:null};plan.items.unshift(item);selected=item.id;changed();select(item.id);});
$('itemForm').addEventListener('submit',event=>{event.preventDefault();countError();const item=plan.items.find(x=>x.id===selected);if(!item)return;const data=new FormData(event.currentTarget), candidate={...item};for(const key of ['title','caseId','department','owner','location','destination','notes','blocker','phase','status'])candidate[key]=String(data.get(key)||'').trim();if(!candidate.title){message('Item name is required.',true);event.currentTarget.elements.title.focus();return}if(!PHASES.includes(candidate.phase)||!STATUSES.includes(candidate.status))return;try{Object.assign(candidate,countPair(data.get('requestedQty'),data.get('packedQty')))}catch(error){countError(error.message);message(error.message,true);event.currentTarget.elements.packedQty.focus();$('countHelp').scrollIntoView({block:'nearest'});return}Object.assign(item,candidate);changed();$('detail').classList.remove('open');$('rows').focus();});
for(const key of ['requestedQty','packedQty'])$('itemForm').elements[key].addEventListener('input',()=>countError());
$('closeDetail').addEventListener('click',()=>{$('detail').classList.remove('open');$('rows').querySelector('.selected')?.focus()});
$('deleteBtn').addEventListener('click',()=>{if(!selected||!confirm('Remove this item from The Shop? The original source record stays saved.'))return;plan.items=plan.items.filter(x=>x.id!==selected);selected=null;changed();$('detail').classList.remove('open');$('addBtn').focus();});
$('saveBtn').addEventListener('click',()=>{if(blocked&&!recoveryAuthorized)return message('Existing saved plan is unreadable. Preview a valid Shop backup to recover it.',true);try{const current=storage.getItem(KEY);if(current!==savedBytes){message('Saved plan changed in another tab. Export this work, then reload.',true);return}const bytes=JSON.stringify({...validatePlan(plan),savedAt:new Date().toISOString()});if(recoveryAuthorized&&savedBytes!==null){recoveryKey ||= 'sbd.shop.recovery.'+crypto.randomUUID();storage.setItem(recoveryKey,savedBytes);if(storage.getItem(recoveryKey)!==savedBytes)throw new Error('Could not preserve the unreadable original');}storage.setItem(KEY,bytes);const recovered=recoveryAuthorized;savedBytes=bytes;blocked=false;recoveryAuthorized=false;dirty=false;message(recovered?'Recovered plan saved; unreadable original preserved in browser storage':'Saved to this browser');}catch(error){message(`Save failed: ${error.message}. Export this plan.`,true)}});
$('exportBtn').addEventListener('click',()=>{const exportingOriginal=blocked&&!recoveryAuthorized&&savedBytes;const data=exportingOriginal?savedBytes:JSON.stringify({...plan,exportedAt:new Date().toISOString()},null,2),url=URL.createObjectURL(new Blob([data],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=exportingOriginal?'the-shop-unreadable-original.json':'the-shop-plan.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);message('JSON backup downloaded');});
function setTheme(mode){
  document.documentElement.setAttribute('data-av-theme',mode);
  const dark=mode==='dark'||(mode==='system'&&matchMedia('(prefers-color-scheme: dark)').matches);
  $('themeBtn').textContent=dark?'Light mode':'Dark mode';
  document.querySelector('[data-av-theme-color=light]').media=mode==='light'?'all':mode==='dark'?'not all':'(prefers-color-scheme: light)';
  document.querySelector('[data-av-theme-color=dark]').media=mode==='dark'?'all':mode==='light'?'not all':'(prefers-color-scheme: dark)';
}
$('themeBtn').addEventListener('click',()=>{
  const current=document.documentElement.getAttribute('data-av-theme');
  const dark=current==='dark'||(current==='system'&&matchMedia('(prefers-color-scheme: dark)').matches);
  const next=dark?'light':'dark';
  setTheme(next);
  try{storage.setItem('av-theme-mode.v1',next)}catch{message('Theme choice is session only.',true)}
});
try{
  const shared=storage.getItem('av-theme-mode.v1');
  const legacy=storage.getItem('sbd.shop.theme.v1');
  if(!shared&&(legacy==='dark'||legacy==='light'))setTheme(legacy);
}catch{}
setTheme(document.documentElement.getAttribute('data-av-theme')||'dark');
function clearPreview(){pending=null;pendingPlan=null;pendingOrigin=null;$('confirmImport').disabled=true;}
$('importBtn').addEventListener('click',()=>{clearPreview();$('importPreview').textContent='Select a source to preview.';$('importDialog').showModal();});
$('sourceKind').addEventListener('change',()=>{clearPreview();$('importPreview').textContent='Select a source to preview.';});
function preview(kind,text,origin=null){try{const payload=JSON.parse(text);if(kind==='shop-backup'){pendingPlan=validatePlan(payload);pending=pendingPlan.items;pendingOrigin=null;$('importPreview').textContent=`${pending.length} Shop rows ready to restore. Confirming will replace the current in-memory plan; Save is still required.`;$('confirmImport').disabled=false;return}pendingPlan=null;pending=stageLegacy(kind,payload);assertFreshSourceRows(plan.items,pending);pendingOrigin=origin;$('importPreview').innerHTML=`<strong>${pending.length} rows ready to copy</strong><br>${pending.slice(0,8).map(x=>`${esc(x.title)} · ${esc(quantityLabel(x))}`).join('<br>')}${pending.length>8?'<br>…':''}`;$('confirmImport').disabled=!pending.length;}catch(error){clearPreview();$('importPreview').textContent=error.message;}}
$('readSource').addEventListener('click',()=>{const kind=$('sourceKind').value;try{if(kind==='shop-backup')throw new Error('Choose a Shop JSON backup file.');const bytes=storage.getItem(SOURCES[kind].key);if(!bytes)throw new Error(`No saved ${SOURCES[kind].label} plan found in this browser.`);preview(kind,bytes,{kind,bytes})}catch(error){clearPreview();$('importPreview').textContent=error.message}});
$('importFile').addEventListener('change',async event=>{const file=event.target.files?.[0];if(!file)return;try{if(file.size>5_000_000)throw new Error('File is too large (5 MB limit).');preview($('sourceKind').value,await file.text())}catch(error){clearPreview();$('importPreview').textContent=error.message}event.target.value=''});
$('confirmImport').addEventListener('click',()=>{if(!pending||(blocked&&!pendingPlan))return;try{if(pendingOrigin&&storage.getItem(SOURCES[pendingOrigin.kind].key)!==pendingOrigin.bytes)throw new Error('Saved source changed after preview. Preview it again.');if(!pendingPlan)assertFreshSourceRows(plan.items,pending)}catch(error){clearPreview();$('importPreview').textContent=error.message;return}if(pendingPlan){if(!confirm(blocked?'Restore this valid backup? The unreadable saved original will be preserved before Save replaces it.':'Replace the current in-memory Shop plan with this backup? Saved data remains until you Save.'))return;recoveryAuthorized=blocked;plan=pendingPlan;$('planName').value=plan.name}else plan.items.push(...pending);const count=pending.length;clearPreview();selected=null;changed();$('importDialog').close();message(`${count} rows loaded. Review and save.`);$('addBtn').focus();});
$('importDialog').addEventListener('close',()=>{clearPreview();$('importBtn').focus()});
window.addEventListener('beforeunload',event=>{if(dirty){event.preventDefault();event.returnValue=''}});
document.addEventListener('keydown',event=>{if(event.key==='Escape'&&$('detail').classList.contains('open')&&!$('importDialog').open){$('detail').classList.remove('open');$('rows').querySelector('.selected')?.focus()}});
load();
