const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const path = require('node:path');
(async()=>{
 const browser=await chromium.launch({headless:true,args:['--no-sandbox']});
 try {
  for(const viewport of [{width:1440,height:900},{width:375,height:812}]){
   const context=await browser.newContext({viewport});
   const page=await context.newPage();
   const errors=[];page.on('pageerror',e=>errors.push(e.message));
   await page.goto('file://'+path.resolve(__dirname,'index.html'));
   await page.getByRole('button',{name:'Add fixture'}).click();
   await page.locator('[name=unit]').fill('LX-01');
   await page.locator('[name=fixture]').fill('Wash');
   await page.locator('[name=position]').fill('Front truss');
   await page.locator('[name=universe]').fill('1');
   await page.locator('[name=address]').fill('101');
   await page.getByRole('button',{name:'Save plan'}).click();
   await page.reload();
   assert.equal(await page.locator('[name=unit]').inputValue(),'');
   await page.getByRole('button',{name:/LX-01/}).click();
   assert.equal(await page.locator('[name=unit]').inputValue(),'LX-01');
   await page.getByRole('button',{name:'Add fixture'}).click();
   await page.locator('[name=universe]').fill('1');
   await page.locator('[name=address]').fill('00101');
   assert.equal(await page.locator('#conflicts').textContent(),'2');
   await page.locator('[data-tab=handoff]').click();
   await page.locator('#importInput').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{bad')});
   await page.waitForFunction(() => document.getElementById('importPreview').textContent.includes('Import rejected'));
   assert.match(await page.locator('#importPreview').textContent(),/Import rejected/);
   assert.equal(await page.locator('#count').textContent(),'2');
   await page.evaluate(() => localStorage.setItem('lighting-patch.v1', JSON.stringify({schema:'system-by-dave.lighting-patch.v1',meta:{showName:'Legacy show'},items:[{id:'legacy-one',unit:'LEG-01',fixture:'Profile',position:'FOH',status:'focused'}]})));
   await page.getByRole('button',{name:'Review saved Lighting Patch'}).click();
   await page.waitForFunction(() => document.getElementById('confirmImport').hidden === false);
   assert.match(await page.locator('#importPreview').textContent(),/1 fixtures/);
   page.once('dialog',dialog=>dialog.accept());
   await page.getByRole('button',{name:'Replace plan with preview'}).click();
   assert.equal(await page.locator('#count').textContent(),'1');
   assert.equal(await page.evaluate(() => JSON.parse(localStorage.getItem('lighting-patch.v1')).items[0].unit),'LEG-01');
   await page.locator('.skip').focus();
   await page.keyboard.press('Enter');
   assert.equal(await page.evaluate(() => document.activeElement.id),'main');
   const dimensions=await page.evaluate(()=>({h:document.documentElement.scrollHeight,ch:document.documentElement.clientHeight,w:document.documentElement.scrollWidth,cw:document.documentElement.clientWidth}));
   assert.ok(dimensions.h<=dimensions.ch && dimensions.w<=dimensions.cw,JSON.stringify(dimensions));
   assert.deepEqual(errors,[]);
   await page.screenshot({path:`/work/av-lighting-${viewport.width}.png`,fullPage:true});
   await context.close();
  }
  const safety=await browser.newContext({viewport:{width:1440,height:900}});
  await safety.addInitScript(() => localStorage.setItem('sbd.avLighting.v1','{bad'));
  const broken=await safety.newPage(); await broken.goto('file://'+path.resolve(__dirname,'index.html'));
  assert.equal(await broken.locator('#recoveryNotice').isVisible(),true);
  await broken.getByRole('button',{name:'Save plan'}).click();
  assert.equal(await broken.evaluate(() => localStorage.getItem('sbd.avLighting.v1')),'{bad');
  assert.match(await broken.locator('#message').textContent(),/Save blocked/);
  broken.once('dialog',dialog=>dialog.accept());
  await broken.getByRole('button',{name:'Preserve original and enable save'}).click();
  assert.equal(await broken.evaluate(() => Object.keys(localStorage).some(k => k.startsWith('sbd.avLighting.v1.recovery.') && localStorage.getItem(k)==='{bad')),true);
  await broken.getByRole('button',{name:'Save plan'}).click();
  assert.equal(await broken.evaluate(() => JSON.parse(localStorage.getItem('sbd.avLighting.v1')).schema),'system-by-dave.av-lighting.v1');
  await broken.getByRole('button',{name:'Add fixture'}).click();
  const leave=broken.waitForEvent('dialog');
  const click=broken.locator('.back').click({noWaitAfter:true});
  const dialog=await leave; assert.equal(dialog.type(),'beforeunload'); await dialog.dismiss(); await click;
  await safety.close();
  const failedCopy=await browser.newContext();
  await failedCopy.addInitScript(() => {localStorage.setItem('sbd.avLighting.v1','{bad');const original=Storage.prototype.setItem;Storage.prototype.setItem=function(key,value){if(key.startsWith('sbd.avLighting.v1.recovery.'))throw new Error('quota');return original.call(this,key,value);};});
  const failedPage=await failedCopy.newPage();await failedPage.goto('file://'+path.resolve(__dirname,'index.html'));
  failedPage.once('dialog',dialog=>dialog.accept());
  await failedPage.getByRole('button',{name:'Preserve original and enable save'}).click();
  assert.match(await failedPage.locator('#message').textContent(),/Save remains blocked/);
  await failedPage.getByRole('button',{name:'Save plan'}).click();
  assert.equal(await failedPage.evaluate(() => localStorage.getItem('sbd.avLighting.v1')),'{bad');
  await failedCopy.close();
  const denied=await browser.newContext();
  await denied.addInitScript(() => {const original=Storage.prototype.getItem;Storage.prototype.getItem=function(key){if(key==='sbd.avLighting.v1')throw new Error('denied');return original.call(this,key);};});
  const deniedPage=await denied.newPage();await deniedPage.goto('file://'+path.resolve(__dirname,'index.html'));
  assert.equal(await deniedPage.locator('#recoveryNotice').isVisible(),true);
  assert.equal(await deniedPage.locator('#recoverBtn').isVisible(),false);
  await deniedPage.getByRole('button',{name:'Save plan'}).click();
  assert.match(await deniedPage.locator('#message').textContent(),/Save blocked/);
  await denied.close();
  const noScript=await browser.newContext({javaScriptEnabled:false});
  const inert=await noScript.newPage();await inert.goto('file://'+path.resolve(__dirname,'index.html'));
  assert.equal(await inert.locator('#bootFailure').isVisible(),true);
  assert.equal(await inert.locator('#app').isVisible(),false);
  await noScript.close();
  console.log('Lighting browser probe passed: save/reload, numeric conflict, imports, unreadable recovery, dirty guard, keyboard skip, script failure, viewport bounds, screenshots');
 } finally {await browser.close();}
})().catch(error=>{console.error(error);process.exitCode=1});
