import { KEY, STAGES, emptyDocument, parseDocument, validateDocument, addClient, addVenue, addJob, updateJob } from './model.mjs';
const $ = id => document.getElementById(id);
let doc = emptyDocument(), saved = '', blocked = false, original = null, pending = null, interactive = false;
const source = { advance: '../show-advance.html', change: '../change-order.html', signoff: '../client-signoff.html', handoff: '../show-handoff.html' };
function status(message, error = false) { $('status').textContent = message; $('status').classList.toggle('error', error); }
function download(name, content, type = 'application/json') { const url = URL.createObjectURL(new Blob([content], { type })); const a = document.createElement('a'); a.href = url; a.download = name; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }
function dirty() { return JSON.stringify(doc) !== saved; }
function mark() { status(dirty() ? 'Unsaved changes · Save your document or export a backup.' : original === null ? 'New document · Add records, then save on this device.' : 'Saved on this device. Export a backup for transfer.'); }
function node(tag, content, className) { const element = document.createElement(tag); if (content != null) element.textContent = content; if (className) element.className = className; return element; }
function option(select, value, label) { const element = document.createElement('option'); element.value = value; element.textContent = label; select.append(element); }
function render() {
  $('stats').replaceChildren();
  for (const [value, label] of [[doc.clients.length, 'Clients'], [doc.venues.length, 'Venues'], [doc.jobs.filter(job => job.stage !== 'Complete').length, 'Open jobs'], [doc.jobs.filter(job => job.stage === 'Complete').length, 'Complete']]) { const card = node('div', null, 'stat'); card.append(node('strong', value), node('span', label)); $('stats').append(card); }
  for (const [id, rows, detail] of [['clients', doc.clients, 'contact'], ['venues', doc.venues, 'location']]) { const list = $(id); list.replaceChildren(); rows.forEach(row => { const item = node('li'); item.append(node('strong', row.name)); if (row[detail]) item.append(node('small', row[detail])); if (row.notes) item.append(node('p', row.notes)); list.append(item); }); if (!rows.length) list.append(node('li', 'No records yet.', 'empty')); }
  const form = $('job-form'); for (const [name, rows] of [['clientId', doc.clients], ['venueId', doc.venues]]) { const select = form.elements[name]; select.replaceChildren(); option(select, '', `Choose ${name === 'clientId' ? 'client' : 'venue'}`); rows.forEach(row => option(select, row.id, row.name)); }
  $('job-hint').hidden = doc.clients.length > 0 && doc.venues.length > 0;
  form.querySelector('button').disabled = !($('job-hint').hidden);
  const jobs = $('jobs'); jobs.replaceChildren(); const selected = $('filter').value; const visible = doc.jobs.filter(job => selected === 'all' || job.stage === selected);
  visible.forEach(job => { const client = doc.clients.find(row => row.id === job.clientId), venue = doc.venues.find(row => row.id === job.venueId); const card = node('article', null, 'job'); const top = node('div', null, 'job-top'); const title = node('div'); title.append(node('h3', job.name), node('p', `${client.name} · ${venue.name}`)); top.append(title, node('span', job.stage, 'badge')); card.append(top);
    const form = node('form', null, 'update-form'); form.hidden = !interactive; form.dataset.id = job.id; const stageLabel = node('label', 'Stage'); const stage = node('select'); stage.name = 'stage'; STAGES.forEach(value => option(stage, value, value)); stage.value = job.stage; stageLabel.append(stage); const nextLabel = node('label', 'Next action'); const next = node('input'); next.name = 'nextAction'; next.maxLength = 2000; next.value = job.nextAction; nextLabel.append(next); const noteLabel = node('label', 'Add update'); const note = node('textarea'); note.name = 'note'; note.maxLength = 500; note.placeholder = 'Decision, change, approval, or handoff note'; noteLabel.append(note); const button = node('button', 'Update job'); form.append(stageLabel, nextLabel, noteLabel, button); card.append(form);
    if (job.nextAction) card.append(node('p', `Next: ${job.nextAction}`, 'next-action'));
    if (job.updates.length) { const log = node('details'); const summary = node('summary', `${job.updates.length} update${job.updates.length === 1 ? '' : 's'}`); log.append(summary); const list = node('ol'); job.updates.forEach(update => { const item = node('li'); item.append(node('time', update.date), node('p', update.body)); list.append(item); }); log.append(list); card.append(log); }
    const links = node('div', null, 'tool-links'); for (const [key, label] of [['advance', 'Show Advance'], ['change', 'Change Order'], ['signoff', 'Client Sign Off'], ['handoff', 'Show Handoff']]) { const a = node('a', label); a.href = source[key]; links.append(a); } card.append(links); jobs.append(card); });
  if (!visible.length) jobs.append(node('p', selected === 'all' ? 'No jobs yet. Start with a client and venue.' : `No ${selected.toLowerCase()} jobs.`, 'empty'));
}
function activateForms() { document.querySelectorAll('#workspace form').forEach(form => { form.hidden = false; }); }
function edit(build) { try { const next = validateDocument(build(doc)); doc = next; render(); mark(); return true; } catch (error) { status(`Could not update: ${error.message} Current records are unchanged.`, true); return false; } }
try { const raw = localStorage.getItem(KEY); if (raw !== null) { original = raw; doc = parseDocument(raw); saved = JSON.stringify(doc); } else saved = JSON.stringify(doc); } catch (error) { blocked = true; $('save').disabled = true; $('export').disabled = true; $('recovery').hidden = false; $('workspace').hidden = true; status(`Saved data could not be opened: ${error.message}`, true); }
if (!blocked) { render(); mark(); }
$('client-form').addEventListener('submit', event => { event.preventDefault(); const form = event.currentTarget; if (!form.reportValidity()) return; if (edit(current => addClient(current, form.elements.name.value, form.elements.contact.value, form.elements.notes.value))) form.reset(); form.elements.name.focus(); });
$('venue-form').addEventListener('submit', event => { event.preventDefault(); const form = event.currentTarget; if (!form.reportValidity()) return; if (edit(current => addVenue(current, form.elements.name.value, form.elements.location.value, form.elements.notes.value))) form.reset(); form.elements.name.focus(); });
$('job-form').addEventListener('submit', event => { event.preventDefault(); const form = event.currentTarget; if (!form.reportValidity()) return; if (edit(current => addJob(current, form.elements.name.value, form.elements.clientId.value, form.elements.venueId.value, form.elements.nextAction.value))) form.reset(); form.elements.name.focus(); });
$('jobs').addEventListener('submit', event => { const form = event.target.closest('.update-form'); if (!form) return; event.preventDefault(); const job = doc.jobs.find(row => row.id === form.dataset.id); if (!job) return; const note = form.elements.note.value.trim(); if (note.length > 500) return status('Update is too long.', true); edit(current => updateJob(current, job.id, form.elements.stage.value, form.elements.nextAction.value, note, new Date().toISOString())); });
$('filter').addEventListener('change', render);
$('save').addEventListener('click', () => { if (blocked) return status('Recover the saved original first.', true); try { const current = localStorage.getItem(KEY); if (current !== original) return status('Saved data changed in another tab. Export your current work, then reload before saving.', true); const raw = JSON.stringify(validateDocument(doc)); localStorage.setItem(KEY, raw); original = raw; saved = raw; mark(); } catch (error) { status(`Save failed: ${error.message}. Export a backup.`, true); } });
$('export').addEventListener('click', () => download('front-office-backup.json', JSON.stringify(doc, null, 2)));
$('export-original').addEventListener('click', () => { if (original != null) download('front-office-original.txt', original, 'text/plain'); });
$('start-fresh').addEventListener('click', () => { if (!confirm('Start a new document? The original bytes remain in storage until you save. Export them first.')) return; blocked = false; $('save').disabled = false; $('export').disabled = false; doc = emptyDocument(); saved = original ?? JSON.stringify(doc); $('recovery').hidden = true; $('workspace').hidden = false; render(); activateForms(); mark(); });
$('import-button').addEventListener('click', () => $('import').click());
$('import').addEventListener('change', async event => { const file = event.target.files[0]; event.target.value = ''; if (!file) return; try { if (file.size > 2_000_000) throw new Error('Backup is larger than 2 MB.'); const candidate = parseDocument(await file.text()); pending = candidate; $('import-summary').textContent = `${candidate.clients.length} clients · ${candidate.venues.length} venues · ${candidate.jobs.length} jobs. Replacing affects only this Front Office document. Export your current document first if needed.`; $('import-preview').hidden = false; $('confirm-import').focus(); status('Valid backup ready to review. No saved data has changed.'); } catch (error) { pending = null; $('import-preview').hidden = true; status(`Import rejected: ${error.message}. Current work is unchanged.`, true); } });
$('cancel-import').addEventListener('click', () => { pending = null; $('import-preview').hidden = true; $('import-button').focus(); mark(); });
$('confirm-import').addEventListener('click', () => { if (!pending) return; if (dirty() && !confirm('Replace unsaved Front Office changes? Export a backup first if needed.')) return; doc = pending; pending = null; $('import-preview').hidden = true; if (blocked) { blocked = false; $('save').disabled = false; $('export').disabled = false; $('recovery').hidden = true; $('workspace').hidden = false; } render(); activateForms(); mark(); $('main').focus(); });
window.addEventListener('beforeunload', event => { if (dirty() && !blocked) { event.preventDefault(); event.returnValue = ''; } });

// Controls become active only after every handler is installed.
interactive = true;
$('boot-status').hidden = true;
if (!blocked) activateForms();
