const { chromium } = require('playwright');
const http = require('http');
const fs = require('fs');
const path = require('path');
const assert = require('node:assert/strict');
const root = path.resolve(__dirname, '..');
const server = http.createServer((request, response) => {
  const url = new URL(request.url, 'http://localhost');
  const file = path.resolve(root, '.' + decodeURIComponent(url.pathname), url.pathname.endsWith('/') ? 'index.html' : '');
  if (!file.startsWith(root + path.sep)) return response.writeHead(403).end();
  fs.readFile(file, (error, body) => {
    if (error) return response.writeHead(404).end();
    response.setHeader('Content-Type', file.endsWith('.mjs') || file.endsWith('.js') ? 'text/javascript' : file.endsWith('.css') ? 'text/css' : 'text/html');
    response.end(body);
  });
});
(async () => {
  await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
  const url = `http://127.0.0.1:${server.address().port}/front-office/`;
  const browser = await chromium.launch({ headless: true, executablePath: process.env.CHROMIUM_PATH, args: ['--no-sandbox'] });
  try {
    const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
    page.setDefaultTimeout(8000);
    const errors = [];
    page.on('pageerror', error => errors.push(error.message));
    await page.goto(url);
    await page.locator('#client-form [name=name]').fill('Acme Events');
    await page.locator('#client-form [name=contact]').fill('Alex');
    await page.getByRole('button', { name: 'Add client' }).click();
    assert.equal(await page.locator('#tab-venues').getAttribute('aria-selected'), 'true');
    await page.locator('#venue-form [name=name]').fill('Grand Hall');
    await page.getByRole('button', { name: 'Add venue' }).click();
    assert.equal(await page.locator('#tab-jobs').getAttribute('aria-selected'), 'true');
    await page.locator('#job-form [name=name]').fill('October Gala');
    await page.locator('#job-form [name=clientId]').selectOption({ label: 'Acme Events' });
    await page.locator('#job-form [name=venueId]').selectOption({ label: 'Grand Hall' });
    await page.locator('#job-form [name=nextAction]').fill('Confirm load in');
    await page.getByRole('button', { name: 'Add job' }).click();
    await page.locator('.update-form [name=stage]').selectOption('Advance');
    await page.locator('.update-form [name=note]').fill('Client confirmed date');
    await page.getByRole('button', { name: 'Update job' }).click();
    await page.getByRole('button', { name: 'Save document' }).click();
    assert.match(await page.locator('#status').innerText(), /Saved on this device/);
    await page.reload();
    assert.equal(await page.locator('.job h3').innerText(), 'October Gala');
    assert.equal(await page.locator('.badge').innerText(), 'Advance');
    await page.locator('details summary').click();
    assert.match(await page.locator('details').innerText(), /Client confirmed date/);
    await page.screenshot({ path: path.join(__dirname, 'probe-desktop.png') });
    await page.setViewportSize({ width: 375, height: 812 });
    await page.screenshot({ path: path.join(__dirname, 'probe-phone.png') });
    assert.equal(await page.evaluate(() => document.documentElement.scrollHeight <= document.documentElement.clientHeight && document.documentElement.scrollWidth <= document.documentElement.clientWidth), true);
    await page.locator('#import').setInputFiles({ name: 'bad.json', mimeType: 'application/json', buffer: Buffer.from('{broken') });
    assert.match(await page.locator('#status').innerText(), /Import rejected/);
    assert.equal(await page.locator('.job h3').innerText(), 'October Gala');
    await page.locator('#import').setInputFiles({ name: 'valid.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify({ version: 1, clients: [], venues: [], jobs: [] })) });
    assert.equal(await page.locator('#import-preview').isVisible(), true);
    await page.getByRole('button', { name: 'Cancel' }).click();
    assert.equal(await page.evaluate(() => document.activeElement.id), 'import-button');
    assert.equal(await page.locator('.job h3').innerText(), 'October Gala');
    await page.reload();
    assert.equal(await page.locator('.job h3').innerText(), 'October Gala');
    const originalBytes = await page.evaluate(() => localStorage.getItem('sbd.frontOffice.document.v1'));
    await page.locator('#tab-clients').click();
    await page.locator('#client-form [name=name]').fill('   ');
    await page.getByRole('button', { name: 'Add client' }).click();
    assert.match(await page.locator('#status').innerText(), /Client name is required/);
    assert.equal(await page.locator('#client-form [name=name]').inputValue(), '   ');
    assert.equal(await page.evaluate(() => localStorage.getItem('sbd.frontOffice.document.v1')), originalBytes);
    const fullBytes = await page.evaluate(() => {
      const doc = JSON.parse(localStorage.getItem('sbd.frontOffice.document.v1'));
      while (doc.clients.length < 500) { const i = doc.clients.length; doc.clients.push({ id: `synthetic-${i}`, name: `Synthetic ${i}`, contact: '', notes: '' }); }
      const raw = JSON.stringify(doc); localStorage.setItem('sbd.frontOffice.document.v1', raw); return raw;
    });
    await page.reload();
    await page.locator('#tab-clients').click();
    await page.locator('#client-form [name=name]').fill('Client 501');
    await page.getByRole('button', { name: 'Add client' }).click();
    assert.match(await page.locator('#status').innerText(), /excessive records/);
    assert.equal(await page.locator('#client-form [name=name]').inputValue(), 'Client 501');
    assert.equal(await page.locator('#clients li').count(), 500);
    assert.equal(await page.evaluate(() => localStorage.getItem('sbd.frontOffice.document.v1')), fullBytes);
    const failedBoot = await browser.newPage();
    await failedBoot.route('**/front-office/app.mjs', route => route.abort());
    await failedBoot.goto(url);
    assert.equal(await failedBoot.locator('#boot-status').isVisible(), true);
    assert.equal(await failedBoot.locator('#client-form').isVisible(), false);
    await failedBoot.close();
    await page.evaluate(() => localStorage.setItem('sbd.frontOffice.document.v1', '{broken'));
    await page.reload();
    assert.equal(await page.locator('#recovery').isVisible(), true);
    assert.equal(await page.locator('#save').isDisabled(), true);
    assert.deepEqual(errors, []);
    await page.close();
    console.log('PASS Front Office save/reload, stage/history, import recovery/focus, blank and 501st records, inert boot, desktop/phone screenshots');
  } finally { await browser.close(); server.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; server.close(); });
