// Generated by scripts/build_switcher_guide.mjs from fmp/models/assets/atem-hd8-iso-0.js.
// Reference photographs of the installed HD8 ISO; files, so they load only when shown.
window.ATEM_PHOTOS=["/fmp/models/assets/atem-photo-front.webp","/fmp/models/assets/atem-photo-perspective.webp","/fmp/models/assets/atem-photo-rear.webp","/fmp/models/assets/atem-photo-side.webp"];
