export type Kind = "rooms" | "crew" | "tasks";
export type Source = { id: string; origin: "saved" | "file"; importedAt: string; identity: string; raw: string };
export type Provenance = { sourceId: string; itemId: string; snapshot: Record<string, string> };
export type RecordRow = { id: string; name: string; detail: string; status: string; source?: Provenance; taskSource?: Provenance; crewSource?: Provenance };
export type Document = { schema: string; show: string; date: string; notes: string; rooms: RecordRow[]; crew: RecordRow[]; tasks: RecordRow[]; roomCheckSources: Source[]; taskBoardSources: Source[]; crewCallSources: Source[] };
export type CopyPreview = { raw: string; meta: { showName: string; showDate: string; venue: string; room?: string }; available: Record<string, string>[]; alreadyCopied: number; excluded?: number };
export const SCHEMA: "system-by-dave.show-ops.v1";
export const KEY: "sbd.showOps.document.v1";
export const ROOM_CHECK_KEY: "room-check.v1";
export const TASK_BOARD_KEY: "show-task-board.v1";
export const CREW_CALL_KEY: "crew-call.v1";
export const MAX_ROOM_CHECK_BYTES: number;
export const MAX_TASK_BOARD_BYTES: number;
export const MAX_CREW_CALL_BYTES: number;
export const statuses: Record<Kind, string[]>;
export function empty(): Document;
export function validate(value: unknown): Document;
export function addRecord(doc: Document, kind: Kind, name: string, detail?: string): Document;
export function updateRecord(doc: Document, kind: Kind, id: string, field: string, value: string): Document;
export function handoff(doc: Document): Record<Kind, RecordRow[]>;
export function previewRoomCheck(doc: Document, raw: string): CopyPreview;
export function previewTaskBoard(doc: Document, raw: string): CopyPreview;
export function previewCrewCall(doc: Document, raw: string): CopyPreview;
export function copyRoomCheck(doc: Document, source: CopyPreview, selectedIds: string[], origin: "saved" | "file", importedAt: string, nextId?: () => string): Document;
export function copyTaskBoard(doc: Document, source: CopyPreview, selectedIds: string[], origin: "saved" | "file", importedAt: string, nextId?: () => string): Document;
export function copyCrewCall(doc: Document, source: CopyPreview, selectedIds: string[], origin: "saved" | "file", importedAt: string, nextId?: () => string): Document;
