const { chromium } = require('playwright');
const http = require('node:http');
const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');
const root = path.resolve(__dirname, '..');
let browser;
const server = http.createServer((req,res)=>{
  const pathname = decodeURIComponent(new URL(req.url,'http://localhost').pathname);
  const file = path.join(root,pathname === '/show-ops/' ? 'show-ops/index.html' : pathname);
  if (!file.startsWith(root) || !fs.existsSync(file) || fs.statSync(file).isDirectory()) {res.writeHead(404);res.end();return;}
  res.setHeader('Content-Type',file.endsWith('.mjs')?'text/javascript':file.endsWith('.css')?'text/css':'text/html'); fs.createReadStream(file).pipe(res);
});
(async()=>{
  await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
  browser=await chromium.launch({headless:true,executablePath:process.env.SHOW_OPS_BROWSER || '/ms-playwright/chromium_headless_shell-1228/chrome-headless-shell-linux64/chrome-headless-shell',args:['--no-sandbox']});
  const output=process.env.SHOW_OPS_OUTPUT || '/check/output'; fs.mkdirSync(output,{recursive:true});
  const origin=`http://127.0.0.1:${server.address().port}`;
  const page=await browser.newPage({viewport:{width:1440,height:900}});
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto(origin+'/show-ops/');
  await page.keyboard.press('Tab');
  assert.equal(await page.evaluate(()=>document.activeElement.className),'skip');
  await page.keyboard.press('Enter');
  assert.equal(await page.evaluate(()=>document.activeElement.id),'main');
  await page.locator('#name').fill('Acceptance show');
  await page.locator('#date').fill('2026-10-07');
  await page.getByRole('button',{name:'Rooms',exact:true}).click();
  await page.locator('[name=name]').fill('Main room');
  await page.locator('[name=detail]').fill('Projector check');
  await page.getByRole('button',{name:'Add room'}).click();
  await page.locator('[data-field=status]').selectOption('Ready');
  await page.getByRole('button',{name:'Save show'}).click();
  await page.reload();
  assert.equal(await page.locator('#show-title').textContent(),'Acceptance show');
  await page.getByRole('button',{name:'Rooms',exact:true}).click();
  assert.equal(await page.locator('[data-field=name]').inputValue(),'Main room');
  await page.getByRole('button',{name:'Backup',exact:true}).click();
  await page.locator('#import').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{bad')});
  await page.waitForFunction(()=>document.querySelector('#notice').textContent.length>0);
  assert.match(await page.locator('#notice').textContent(),/JSON|property|Unexpected/);
  assert.equal(await page.locator('#import').inputValue(),'');
  assert.equal(await page.locator('#show-title').textContent(),'Acceptance show');
  const backup={schema:'system-by-dave.show-ops.v1',show:'Restored show',date:'2026-10-08',notes:'',rooms:[],crew:[],tasks:[]};
  await page.locator('#import').setInputFiles({name:'good.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(backup))});
  assert.equal(await page.locator('#confirm-import').count(),1);
  await page.locator('#cancel-import').click();
  assert.equal(await page.locator('#import').inputValue(),'');
  await page.locator('#import').setInputFiles({name:'good.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(backup))});
  await page.locator('#confirm-import').click();
  assert.equal(await page.locator('#show-title').textContent(),'Restored show');
  await page.reload();
  assert.equal(await page.locator('#show-title').textContent(),'Acceptance show');
  const roomRaw=JSON.stringify({schema:'system-by-dave.room-check.v1',savedAt:'2026-10-07T07:00:00Z',meta:{showName:'Acceptance show',showDate:'2026-10-07',venue:'Hall',room:'Main'},items:[
    {id:'room-one',area:'room',check:'Sightlines',owner:'Lead',due:'07:30',priority:'high',status:'ready',blocker:'',notes:'Back row clear',extra:'Preserve this'},
    {id:'room-two',area:'video',check:'DSM route',owner:'V1',due:'08:00',priority:'normal',status:'issue',blocker:'Aux missing',notes:'Check switcher'}
  ]});
  await page.evaluate(raw=>localStorage.setItem('room-check.v1',raw),roomRaw);
  const originalShow=await page.evaluate(()=>localStorage.getItem('sbd.showOps.document.v1'));
  await page.getByRole('button',{name:'Backup',exact:true}).click();
  await page.locator('#room-saved').click();
  assert.equal(await page.locator('input[name="room-check-row"]').count(),2);
  assert.match(await page.locator('#room-preview').textContent(),/Room Check ready/);
  assert.match(await page.locator('#room-preview').textContent(),/Needs check/);
  for(const size of [{width:320,height:256},{width:375,height:812},{width:844,height:390},{width:1440,height:900},{width:3840,height:1080}]){
    await page.setViewportSize(size);
    const bounds=await page.evaluate(()=>({h:document.documentElement.scrollHeight,ch:document.documentElement.clientHeight,w:document.documentElement.scrollWidth,cw:document.documentElement.clientWidth}));
    assert.ok(bounds.h<=bounds.ch && bounds.w<=bounds.cw,JSON.stringify({size,bounds}));
    if([320,375,1440].includes(size.width)) await page.screenshot({path:path.join(output,`show-ops-room-preview-${size.width}.png`)});
    await page.locator('input[name="room-check-row"][value="room-two"]').focus();
    assert.equal(await page.locator('input[name="room-check-row"][value="room-two"]').isVisible(),true);
  }
  await page.setViewportSize({width:1440,height:900});
  await page.locator('#cancel-room').click();
  assert.equal(await page.evaluate(()=>localStorage.getItem('sbd.showOps.document.v1')),originalShow);
  await page.locator('#room-saved').click();
  await page.evaluate(raw=>localStorage.setItem('room-check.v1',raw.replace('Back row clear','Changed after preview')),roomRaw);
  await page.locator('#confirm-room').click();
  assert.match(await page.locator('#notice').textContent(),/changed after preview/);
  assert.equal(await page.evaluate(()=>localStorage.getItem('sbd.showOps.document.v1')),originalShow);
  await page.evaluate(raw=>localStorage.setItem('room-check.v1',raw),roomRaw);
  await page.locator('#room-saved').click();
  await page.evaluate(raw=>localStorage.setItem('sbd.showOps.document.v1',raw.replace('Acceptance show','Changed in another tab')),originalShow);
  await page.locator('#confirm-room').click();
  assert.match(await page.locator('#notice').textContent(),/changed after preview/);
  await page.evaluate(raw=>localStorage.setItem('sbd.showOps.document.v1',raw),originalShow);
  await page.locator('#room-file').setInputFiles({name:'invalid.json',mimeType:'application/json',buffer:Buffer.from('{bad')});
  await page.waitForFunction(()=>document.querySelector('#notice').textContent.includes('could not be parsed'));
  assert.match(await page.locator('#notice').textContent(),/could not be parsed/);
  await page.locator('#room-saved').click();
  await page.locator('input[name="room-check-row"][value="room-two"]').uncheck();
  await page.locator('#confirm-room').click();
  assert.equal(await page.locator('.record').count(),2);
  assert.match(await page.locator('.source-fields summary').textContent(),/Original Room Check: ready/);
  assert.equal(await page.locator('#dirty').textContent(),'Unsaved edits');
  assert.equal(await page.evaluate(()=>localStorage.getItem('sbd.showOps.document.v1')),originalShow);
  await page.reload();
  await page.getByRole('button',{name:'Rooms',exact:true}).click();
  assert.equal(await page.locator('.record').count(),1);
  await page.getByRole('button',{name:'Backup',exact:true}).click();
  await page.locator('#room-saved').click();
  await page.locator('input[name="room-check-row"][value="room-two"]').uncheck();
  await page.locator('#confirm-room').click();
  await page.locator('#save').click();
  await page.reload();
  assert.equal(await page.evaluate(()=>localStorage.getItem('room-check.v1')),roomRaw);
  let copied=JSON.parse(await page.evaluate(()=>localStorage.getItem('sbd.showOps.document.v1')));
  assert.equal(copied.roomCheckSources[0].raw,roomRaw);
  assert.equal(copied.rooms[1].status,'Needs check');
  assert.equal(copied.rooms[1].source.snapshot.status,'ready');
  await page.getByRole('button',{name:'Backup',exact:true}).click();
  const downloadPromise=page.waitForEvent('download'); await page.locator('#export').click();
  const downloaded=await downloadPromise;
  const exportedText=fs.readFileSync(await downloaded.path(),'utf8');
  assert.equal(JSON.parse(exportedText).roomCheckSources[0].raw,roomRaw);
  const restored=await browser.newPage({viewport:{width:375,height:812}});
  await restored.goto(origin+'/show-ops/');
  await restored.getByRole('button',{name:'Backup',exact:true}).click();
  await restored.locator('#import').setInputFiles({name:'show-ops-backup.json',mimeType:'application/json',buffer:Buffer.from(exportedText)});
  await restored.locator('#confirm-import').click();
  await restored.locator('#save').click();
  await restored.reload();
  assert.equal(JSON.parse(await restored.evaluate(()=>localStorage.getItem('sbd.showOps.document.v1'))).roomCheckSources[0].raw,roomRaw);
  await restored.close();
  await page.locator('#room-file').setInputFiles({name:'room-check.json',mimeType:'application/json',buffer:Buffer.from(roomRaw)});
  await page.locator('#confirm-room').waitFor();
  assert.match(await page.locator('#room-preview').textContent(),/1 previously copied/);
  await page.locator('#confirm-room').click();
  await page.locator('#save').click();
  await page.reload();
  copied=JSON.parse(await page.evaluate(()=>localStorage.getItem('sbd.showOps.document.v1')));
  assert.equal(copied.rooms.length,3);
  assert.equal(copied.rooms[2].source.snapshot.blocker,'Aux missing');
  await page.getByRole('button',{name:'Backup',exact:true}).click();
  await page.locator('#room-saved').click();
  assert.match(await page.locator('#notice').textContent(),/already copied/);
  assert.equal(await page.evaluate(()=>localStorage.getItem('room-check.v1')),roomRaw);
  const blocked=await browser.newPage({viewport:{width:900,height:700}});
  await blocked.goto(origin+'/show-ops/');
  await blocked.evaluate(()=>localStorage.setItem('sbd.showOps.document.v1',JSON.stringify({schema:'system-by-dave.show-ops.v1',show:'Protected show',date:'2026-10-07',notes:'',rooms:[],crew:[],tasks:[]})));
  await blocked.addInitScript(()=>{const read=Storage.prototype.getItem;window.__rawRead=key=>read.call(localStorage,key);Storage.prototype.getItem=function(key){if(key==='sbd.showOps.document.v1') throw new Error('Read blocked');return read.call(this,key)}});
  await blocked.reload();
  assert.equal(await blocked.locator('#name').count(),1);
  await blocked.locator('#name').fill('Do not overwrite');
  await blocked.locator('#save').click();
  assert.match(await blocked.locator('#notice').textContent(),/Save failed/);
  assert.equal(await blocked.evaluate(()=>window.__rawRead('sbd.showOps.document.v1').includes('Protected show')),true);
  await blocked.close();
  const themeBlocked=await browser.newPage({viewport:{width:900,height:700}});
  await themeBlocked.addInitScript(()=>{const read=Storage.prototype.getItem;Storage.prototype.getItem=function(key){if(key==='av-theme-mode.v1') throw new Error('Theme blocked');return read.call(this,key)}});
  await themeBlocked.goto(origin+'/show-ops/');
  assert.equal(await themeBlocked.locator('#name').count(),1);
  await themeBlocked.locator('#name').fill('Still usable');
  await themeBlocked.locator('#save').click();
  assert.match(await themeBlocked.locator('#notice').textContent(),/Show saved/);
  await themeBlocked.close();
  const failed=await browser.newPage({viewport:{width:900,height:700}});
  await failed.addInitScript(()=>{const original=Storage.prototype.setItem;Storage.prototype.setItem=function(key,value){if(key==='sbd.showOps.document.v1') throw new Error('Quota test');return original.call(this,key,value)}});
  await failed.goto(origin+'/show-ops/');await failed.locator('#name').fill('Unsaved after failure');await failed.locator('#save').click();
  assert.match(await failed.locator('#notice').textContent(),/Save failed/);
  assert.equal(await failed.locator('#name').inputValue(),'Unsaved after failure');
  await failed.reload();
  await failed.evaluate(raw=>localStorage.setItem('room-check.v1',raw),roomRaw);
  await failed.getByRole('button',{name:'Backup',exact:true}).click();
  await failed.locator('#room-saved').click();
  await failed.locator('#confirm-room').click();
  await failed.locator('#save').click();
  assert.match(await failed.locator('#notice').textContent(),/Save failed/);
  assert.equal(await failed.locator('.record').count(),2);
  assert.equal(await failed.evaluate(()=>localStorage.getItem('sbd.showOps.document.v1')),null);
  assert.equal(await failed.evaluate(()=>localStorage.getItem('room-check.v1')),roomRaw);
  await failed.close();
  const concurrent=await browser.newPage({viewport:{width:900,height:700}});
  await concurrent.goto(origin+'/show-ops/');
  await concurrent.locator('#name').fill('Unsaved concurrent edit');
  const otherTab=JSON.stringify({schema:'system-by-dave.show-ops.v1',show:'Other tab',date:'2026-10-07',notes:'',rooms:[],crew:[],tasks:[]});
  await concurrent.evaluate(raw=>localStorage.setItem('sbd.showOps.document.v1',raw),otherTab);
  await concurrent.locator('#save').click();
  assert.match(await concurrent.locator('#notice').textContent(),/Another tab changed/);
  assert.equal(await concurrent.evaluate(()=>localStorage.getItem('sbd.showOps.document.v1')),otherTab);
  await concurrent.close();
  await page.screenshot({path:path.join(output,'show-ops-desktop.png'),fullPage:true});
  for(const size of [{width:1440,height:900},{width:375,height:812},{width:2560,height:720}]){
    await page.setViewportSize(size);const bounds=await page.evaluate(()=>({h:document.documentElement.scrollHeight,ch:document.documentElement.clientHeight,w:document.documentElement.scrollWidth,cw:document.documentElement.clientWidth}));if(bounds.w>bounds.cw) console.log(await page.evaluate(()=>[...document.querySelectorAll("*")].filter(e=>e.getBoundingClientRect().right>innerWidth).slice(0,8).map(e=>[e.tagName,e.className,e.getBoundingClientRect().right])));assert.ok(bounds.h<=bounds.ch && bounds.w<=bounds.cw,JSON.stringify({size,bounds}));
  }
  await page.setViewportSize({width:375,height:812});
  await page.screenshot({path:path.join(output,'show-ops-phone.png'),fullPage:true});
  const themePage=await browser.newPage();
  const themeErrors=[]; themePage.on('pageerror',error=>themeErrors.push(error.message));
  await themePage.goto(origin+'/show-ops/');
  for (const mode of ['light','dark']) {
    await themePage.evaluate(value=>localStorage.setItem('av-theme-mode.v1',value),mode);
    for (const size of [{width:390,height:844},{width:1440,height:900}]) {
      await themePage.setViewportSize(size); await themePage.reload();
      const appearance=await themePage.evaluate(()=>{
        const root=document.documentElement, style=getComputedStyle(root);
        const token=name=>style.getPropertyValue(name).trim().toLowerCase();
        const color=element=>getComputedStyle(element).color;
        return {tool:root.dataset.avTool,mode:root.dataset.avTheme,bg:token('--av-bg'),surface:token('--av-surface'),text:token('--av-text'),accent:token('--av-accent'),primaryInk:token('--av-primary-ink'),eyebrow:color(document.querySelector('main .eyebrow')),badge:color(document.querySelector('.badge')),button:color(document.querySelector('.primary')),overflow:root.scrollWidth-root.clientWidth};
      });
      assert.equal(appearance.tool,'show-ops'); assert.equal(appearance.mode,mode);
      assert.equal(appearance.bg,mode==='light'?'#eee8df':'#0c1016'); assert.ok(appearance.overflow<=1);
      const channels=value=>value.startsWith('#')?value.slice(1).match(/../g).map(v=>parseInt(v,16)):value.match(/[\d.]+/g).slice(0,3).map(Number);
      const luminance=value=>channels(value).map(v=>{v/=255;return v<=.04045?v/12.92:((v+.055)/1.055)**2.4}).reduce((sum,v,index)=>sum+v*[.2126,.7152,.0722][index],0);
      const contrast=(a,b)=>{const x=luminance(a),y=luminance(b);return (Math.max(x,y)+.05)/(Math.min(x,y)+.05)};
      assert.ok(contrast(appearance.text,appearance.bg)>=4.5,JSON.stringify(appearance));
      assert.ok(contrast(appearance.eyebrow,appearance.bg)>=4.5,JSON.stringify(appearance));
      assert.ok(contrast(appearance.badge,appearance.bg)>=4.5,JSON.stringify(appearance));
      assert.ok(contrast(appearance.button,appearance.accent)>=4.5,JSON.stringify(appearance));
      await themePage.locator('#name').fill(`${mode} ${size.width} operator`);
      await themePage.locator('#save').click(); await themePage.reload();
      assert.equal(await themePage.locator('#name').inputValue(),`${mode} ${size.width} operator`);
      await themePage.screenshot({path:path.join(output,`show-ops-${mode}-${size.width}.png`),fullPage:true});
    }
  }
  await themePage.locator('#theme').click();
  assert.equal(await themePage.evaluate(()=>document.documentElement.dataset.avTheme),'light');
  await themePage.reload();
  assert.equal(await themePage.evaluate(()=>document.documentElement.dataset.avTheme),'light');
  assert.deepEqual(themeErrors,[]);
  await themePage.close();
  assert.deepEqual(errors,[]);
  console.log('Show Ops browser acceptance passed: save/reload, valid and invalid import, desktop/phone/ultrawide no page scroll, screenshots.');
  await browser.close(); server.close();
})().catch(async error=>{console.error(error);await browser?.close();server.close();process.exitCode=1});
