const assert=require('node:assert/strict'),fs=require('node:fs/promises'),{chromium,webkit}=require('playwright');
(async()=>{
 const browser=await(process.env.VIEWPORT_BROWSER==='webkit'?webkit.launch():chromium.launch({channel:'chrome'}));
 const context=await browser.newContext({viewport:{width:375,height:812},reducedMotion:'reduce',acceptDownloads:true}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
 await page.goto((process.env.VIEWPORT_BASE||'http://localhost:4173/')+'show-board.html');await page.waitForSelector('[data-av-viewport=ready]');
 async function activate(id){await page.evaluate(id=>{const u=new URL(location.href);u.searchParams.set('taskView',id);history.pushState(null,'',u);dispatchEvent(new PopStateEvent('popstate'));},id);}
 async function reveal(selector){const view=await page.locator(selector).evaluate(n=>n.closest('.av-board-view')?.id);if(view!=='setup'&&view!=='sheet')await activate(view);const card=page.locator('#'+view);const prev=card.getByRole('button',{name:'Previous',exact:true});while(await prev.isEnabled())await prev.click();for(let n=0;n<40&&!await page.locator(selector).isVisible();n++)await card.getByRole('button',{name:'Next',exact:true}).click();assert(await page.locator(selector).isVisible());}
 for(const[id,value]of [['s_name','Viewport fixture'],['s_venue','Test venue'],['s_rooms','Main | Floor 1\nBreakout | Floor 2']]){await reveal('#'+id);await page.locator('#'+id).fill(value);}
 await reveal('#s_create');await page.locator('#s_create').click();await page.waitForFunction(()=>!document.body.classList.contains('setup'));
 await activate('timelineView');assert.equal(await page.locator('.rlabel').count(),2);
 await page.locator('.rlabel').first().click();await page.waitForSelector('#sheet.open .av-items');await reveal('#f_iss');await page.locator('#f_iss').fill('Fixture battery issue');await reveal('#f_add');await page.locator('#f_add').click();await page.waitForFunction(()=>document.getElementById('isslist')?.textContent.includes('Fixture battery issue'));
 await reveal('#f_cancel');await page.locator('#f_cancel').click();await page.waitForTimeout(300);
 await reveal('#editbtn');await page.locator('#editbtn').click();await activate('timelineView');await page.locator('.rlabel').first().click();await page.waitForSelector('#sheet.open .av-items');await reveal('#f_add');await page.locator('#f_add').click();await page.waitForSelector('#f_s',{state:'attached'});
 for(const [id,value] of [['f_s','09:00'],['f_e','10:00'],['f_id','101']]){await reveal('#'+id);await page.locator('#'+id).fill(value);}
 await reveal('#f_save');await page.locator('#f_save').click();await reveal('#editbtn');await page.locator('#editbtn').click();await activate('timelineView');await page.locator('.blk').first().click();assert.equal(await page.locator('.blk').first().getAttribute('aria-pressed'),'true');await page.waitForTimeout(300);
 await reveal('#backupbtn');let download=page.waitForEvent('download');await page.locator('#backupbtn').click();const payload=JSON.parse(await fs.readFile(await(await download).path(),'utf8'));assert.equal(payload.name,'Viewport fixture');assert.equal(payload.days[0].rooms.length,2);assert(JSON.stringify(payload).includes('Fixture battery issue'));
 await reveal('#backupsbtn');await page.locator('#backupsbtn').click();await page.waitForSelector('#snapshotlist',{state:'attached'});await reveal('#snapshotlist');assert(await page.locator('#snapshotlist').textContent());await page.keyboard.press('Escape');
 await page.locator('#s_file').setInputFiles({name:'roundtrip.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(payload))});await page.waitForTimeout(600);
 await reveal('#backupbtn');download=page.waitForEvent('download');await page.locator('#backupbtn').click();const repeated=JSON.parse(await fs.readFile(await(await download).path(),'utf8'));assert.deepEqual(repeated.days,payload.days);assert.deepEqual(repeated.zones,payload.zones);
 await page.locator('#viewportTheme').click();await page.reload();await page.waitForSelector('[data-av-viewport=ready]');assert.equal(await page.locator('html').getAttribute('data-av-theme'),'dark');assert(await page.locator('body').evaluate(n=>n.classList.contains('dark')));
 await activate('timelineView');assert.equal(await page.locator('.rlabel').count(),2);
 const other=await context.newPage();await other.goto((process.env.VIEWPORT_BASE||'http://localhost:4173/')+'show-board.html');
 await other.evaluate(()=>{const index=JSON.parse(localStorage.getItem('sbd.showboard.index'));const key='sbd.showboard.show.'+index.active;const data=JSON.parse(localStorage.getItem(key));data.revision+=1;data.writeToken='controlled-conflict-fixture';data.name='Newer fixture';localStorage.setItem(key,JSON.stringify(data));});
 await page.waitForFunction(()=>!document.getElementById('keepminebtn').hidden);assert(await page.locator('#recoveryView').isVisible());await reveal('#reloadbtn');await page.locator('#reloadbtn').click();await page.waitForFunction(()=>document.getElementById('showname').textContent.includes('Newer fixture'));await other.close();
 await page.evaluate(()=>dispatchEvent(new Event('beforeprint')));await page.emulateMedia({media:'print'});for(const node of await page.locator('#app>.av-board-view').all())assert(await node.isVisible());assert.deepEqual(errors,[]);await browser.close();console.log('PASS Show Board create, room operations, issue, snapshots, conflict recovery, export/import identity and geometry, theme/reload, print');
})().catch(e=>{console.error(e);process.exit(1)});
