const assert=require('node:assert/strict'),fs=require('node:fs/promises'),{chromium,webkit}=require('playwright');
const base=process.env.VIEWPORT_BASE||'http://127.0.0.1:4179/';
(async()=>{const browser=await(process.env.VIEWPORT_BROWSER==='webkit'?webkit.launch():chromium.launch({channel:'chrome'}));const context=await browser.newContext({viewport:{width:375,height:812},reducedMotion:'reduce',acceptDownloads:true}),p=await context.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('dialog',d=>d.accept());await p.goto(base+'cue-sheet.html');await p.waitForSelector('[data-av-viewport=ready]');
async function settle(){await p.evaluate(async()=>{await document.fonts.ready;await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));});}
async function view(id){await p.evaluate(id=>{const u=new URL(location.href);u.searchParams.set('taskView',id);history.pushState(null,'',u);dispatchEvent(new PopStateEvent('popstate'));},id);await settle();}
async function reveal(selector){const id=await p.locator(selector).evaluate(n=>n.closest('.av-view').id);await view(id);const pager=p.locator('#'+id+'>.av-pages');if(await pager.count()){const prev=pager.getByRole('button',{name:'Previous',exact:true});while(await prev.isEnabled()){await prev.click();await settle();}for(let n=0;n<50&&!await p.locator(selector).isVisible();n++){await pager.getByRole('button',{name:'Next',exact:true}).click();await settle();}}assert(await p.locator(selector).isVisible(),selector);}
assert.equal(await p.locator('html').getAttribute('data-av-theme'),'dark');await reveal('#showTitle');await p.locator('#showTitle').fill('Viewport media fixture');
await reveal('[data-quick-add=Audio]');await p.locator('[data-quick-add=Audio]').click();
const wave=Buffer.alloc(44+44100*2*4);wave.write('RIFF');wave.writeUInt32LE(wave.length-8,4);wave.write('WAVEfmt ',8);wave.writeUInt32LE(16,16);wave.writeUInt16LE(1,20);wave.writeUInt16LE(1,22);wave.writeUInt32LE(44100,24);wave.writeUInt32LE(88200,28);wave.writeUInt16LE(2,32);wave.writeUInt16LE(16,34);wave.write('data',36);wave.writeUInt32LE(wave.length-44,40);
await p.locator('#sourceFileInput').setInputFiles({name:'controlled-silence.wav',mimeType:'audio/wav',buffer:wave});await p.waitForSelector('#previewSurface audio',{state:'attached'});await reveal('#previewPlayBtn');await p.locator('#previewPlayBtn').click();await p.waitForFunction(()=>{const a=document.querySelector('#previewSurface audio');return a&&!a.paused&&a.currentTime>0;});
await p.evaluate(()=>{window.fixtureMedia=document.querySelector('#previewSurface audio');window.fixtureTime=window.fixtureMedia.currentTime;});await view('setupView');await view('editView');await view('operateView');assert(await p.evaluate(()=>window.fixtureMedia===document.querySelector('#previewSurface audio')&&!window.fixtureMedia.paused&&window.fixtureMedia.currentTime>=window.fixtureTime),'view changes preserve playing media node and time');
await p.locator('#goLiveBtn').click();await p.waitForSelector('#programSurface audio',{state:'attached'});const live=await p.evaluate(()=>JSON.parse(localStorage.getItem('cueSheet.v1')).activeLayers);assert(Object.keys(live).length);
await reveal('#openOutputBtn');const popupPromise=p.waitForEvent('popup');await p.locator('#openOutputBtn').click();const popup=await popupPromise;await popup.waitForSelector('#cueSheetProgramRoot audio',{state:'attached'});assert(await popup.locator('#cueSheetProgramRoot audio').evaluate(n=>n.src.startsWith('blob:')));await popup.close();
await reveal('[data-quick-add=Video]');await p.locator('[data-quick-add=Video]').click();await p.locator('#sourceFileInput').setInputFiles(require('node:path').join(__dirname,'fixtures/viewport-blue.mp4'));await p.waitForSelector('#previewSurface video',{state:'attached'});await reveal('#previewPlayBtn');await p.locator('#previewPlayBtn').click();await p.waitForFunction(()=>{const v=document.querySelector('#previewSurface video');return v&&!v.paused&&v.currentTime>0;});await p.evaluate(()=>{window.fixtureVideo=document.querySelector('#previewSurface video');window.videoTime=window.fixtureVideo.currentTime;});await view('setupView');await view('operateView');assert(await p.evaluate(()=>window.fixtureVideo===document.querySelector('#previewSurface video')&&!window.fixtureVideo.paused&&window.fixtureVideo.currentTime>=window.videoTime),'view changes preserve playing video');await p.locator('#goLiveBtn').click();await p.waitForSelector('#programSurface video',{state:'attached'});
await reveal('#exportJsonBtn');let download=p.waitForEvent('download');await p.locator('#exportJsonBtn').click();const payload=JSON.parse(await fs.readFile(await(await download).path(),'utf8'));assert.equal(payload.schema,'system-by-dave.cue-sheet.v2');
await p.locator('#importFile').setInputFiles({name:'roundtrip.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(payload))});await p.waitForTimeout(300);await reveal('#exportJsonBtn');download=p.waitForEvent('download');await p.locator('#exportJsonBtn').click();const repeated=JSON.parse(await fs.readFile(await(await download).path(),'utf8'));delete payload.exportedAt;delete repeated.exportedAt;assert.deepEqual(repeated,payload);
const saved=await p.evaluate(()=>localStorage.getItem('cueSheet.v1'));await p.locator('#importFile').setInputFiles({name:'invalid.json',mimeType:'application/json',buffer:Buffer.from('{bad')});await p.waitForFunction(()=>document.getElementById('hint').classList.contains('error'));assert(await p.locator('#hint').isVisible());assert.equal(await p.evaluate(()=>localStorage.getItem('cueSheet.v1')),saved);
await p.locator('#viewportTheme').click();await p.reload();await p.waitForSelector('[data-av-viewport=ready]');assert.equal(await p.locator('html').getAttribute('data-av-theme'),'light');assert.equal(await p.evaluate(()=>JSON.parse(localStorage.getItem('cueSheet.v1')).title),'Viewport media fixture');
await view('operateView');await p.keyboard.press('j');await p.keyboard.press('k');await p.keyboard.press('f');await p.waitForFunction(()=>!document.getElementById('editView').hidden);await p.keyboard.press('Escape');await p.waitForFunction(()=>!document.getElementById('operateView').hidden);
await p.evaluate(()=>dispatchEvent(new Event('beforeprint')));await p.emulateMedia({media:'print'});await settle();assert(await p.locator('#cueBody').isVisible());assert((await p.locator('.av-print-text').allTextContents()).includes('Viewport media fixture'));assert.deepEqual(errors,[]);await browser.close();console.log('PASS Cue Sheet media continuity, output window, all-field export/import, invalid import, state/theme reload, shortcuts, print');})().catch(e=>{console.error(e);process.exit(1)});
