const assert=require('node:assert/strict'),fs=require('node:fs/promises'),{chromium,webkit}=require('playwright');
(async()=>{const engine=process.env.VIEWPORT_BROWSER||'chromium',b=await(engine==='webkit'?webkit.launch():chromium.launch({channel:'chrome'})),c=await b.newContext({viewport:{width:375,height:812},hasTouch:true,reducedMotion:'reduce',acceptDownloads:true}),p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('dialog',d=>d.accept());await p.goto((process.env.VIEWPORT_BASE||'http://127.0.0.1:4183/')+'stage-plot.html');await p.waitForSelector('[data-av-viewport=ready]');
async function settle(){await p.evaluate(async()=>{await document.fonts.ready;await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));});}
async function view(id){await p.evaluate(id=>{const u=new URL(location.href);u.searchParams.set('taskView',id);history.pushState(null,'',u);dispatchEvent(new PopStateEvent('popstate'));},id);await settle();}
async function reveal(selector){const id=await p.locator(selector).evaluate(n=>n.closest('.av-view').id);await view(id);const pager=p.locator('#'+id+'>.av-pages');if(await pager.count()){const prev=pager.getByRole('button',{name:'Previous',exact:true});while(await prev.isEnabled()){await prev.click();await settle();}for(let i=0;i<40&&!await p.locator(selector).isVisible();i++){await pager.getByRole('button',{name:'Next',exact:true}).click();await settle();}}assert(await p.locator(selector).isVisible(),selector);}
const state=()=>p.evaluate(()=>JSON.parse(localStorage.getItem('stage-plot.v1')));
await reveal('#itemType');await p.locator('#itemType').selectOption('camera');await reveal('#itemLabel');await p.locator('#itemLabel').fill('Viewport camera');await reveal('#addItemBtn');await p.locator('#addItemBtn').click();assert(await p.locator('#canvasView').isVisible());let before=await state(),id=before.selectedId;assert(before.items.some(x=>x.id===id&&x.label==='Viewport camera'));
for(const[selector,value]of [['#editX','30'],['#editY','30'],['#editW','12'],['#editH','10'],['#editRotation','15'],['#editNotes','Fixture cable path and placement notes']]){await reveal(selector);await p.locator(selector).fill(value);await p.locator(selector).press('Tab');}await p.waitForTimeout(250);before=await state();const item=before.items.find(x=>x.id===id);assert.equal(item.x,30);assert.equal(item.y,30);assert.equal(item.rotation,15);assert.equal(item.w,12);assert.equal(item.h,10);
await view('canvasView');await p.locator('#plotZoomIn').click();await p.locator('#plotZoomIn').click();assert.equal(await p.locator('#plotViewport').getAttribute('data-zoom'),'2.25');assert.deepEqual(await state(),before,'view zoom does not change document geometry');
await p.locator('#plotPan').click();await p.locator('#plotViewport').focus();await p.keyboard.press('ArrowLeft');assert.deepEqual(await state(),before,'pan keyboard does not nudge items');await p.locator('#plotPan').click();await p.locator('#plotFit').click();
const target=p.locator('.plot-item[data-id="'+id+'"]');await target.click();const box=await target.boundingBox(),surface=await p.locator('#plotSurface').boundingBox();await p.mouse.move(box.x+box.width/2,box.y+box.height/2);await p.mouse.down();await p.mouse.move(box.x+box.width/2+surface.width*.08,box.y+box.height/2+surface.height*.06,{steps:5});await p.mouse.up();await p.waitForTimeout(250);let moved=(await state()).items.find(x=>x.id===id);assert.equal(moved.x,38);assert.equal(moved.y,36);assert.equal(moved.w,12);assert.equal(moved.rotation,15);
if(engine==='chromium'){const cd=await c.newCDPSession(p),box=await target.boundingBox();await cd.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:box.x+box.width/2,y:box.y+box.height/2}]});await cd.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:box.x+box.width/2+surface.width*.04,y:box.y+box.height/2}]});await cd.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await p.waitForTimeout(250);assert.equal((await state()).items.find(x=>x.id===id).x,42);}
await p.locator('#plotSurface').focus();const x=(await state()).items.find(x=>x.id===id).x;await p.keyboard.press('ArrowRight');assert.equal((await state()).items.find(x=>x.id===id).x,x+2);
await p.setViewportSize({width:1440,height:900});await p.locator('#canvasViewTab').focus();before=await state();await p.keyboard.press('ArrowRight');assert.deepEqual(await state(),before,'task navigation arrows do not nudge plot items');await p.goBack();assert(await p.locator('#canvasView').isVisible());
await reveal('#exportJsonBtn');let download=p.waitForEvent('download');await p.locator('#exportJsonBtn').click();const payload=JSON.parse(await fs.readFile(await(await download).path(),'utf8'));assert.equal(payload.schema,'system-by-dave.plotforge.v1');await p.locator('#jsonInput').setInputFiles({name:'roundtrip.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(payload))});await p.waitForTimeout(250);await reveal('#exportJsonBtn');download=p.waitForEvent('download');await p.locator('#exportJsonBtn').click();const repeated=JSON.parse(await fs.readFile(await(await download).path(),'utf8'));delete payload.exportedAt;delete repeated.exportedAt;assert.deepEqual(repeated,payload);
const saved=await state();await p.locator('#jsonInput').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{bad')});await p.waitForFunction(()=>document.getElementById('message').classList.contains('error'));assert(await p.locator('#message').isVisible());assert.deepEqual(await state(),saved);await p.locator('#viewportTheme').click();await p.reload();await p.waitForSelector('[data-av-viewport=ready]');assert.equal(await p.locator('html').getAttribute('data-av-theme'),'light');assert.deepEqual((await state()).items,saved.items);
await p.evaluate(()=>dispatchEvent(new Event('beforeprint')));await p.emulateMedia({media:'print'});await settle();assert(await p.locator('#plotSurface').isVisible());assert.equal(await p.locator('.plot-item:visible').count(),saved.items.length);assert((await p.locator('.av-print-text').allTextContents()).some(t=>t.includes('Fixture cable path')));assert.deepEqual(errors,[]);await b.close();console.log('PASS StagePlotter geometry, mouse/touch pointer placement, view zoom/pan, keyboard, field/identity round trip, errors, save/theme reload, print');})().catch(e=>{console.error(e);process.exit(1)});
