import {KEY, TYPES, blank, validPlan, legacyPreview, mergeLegacy, counts, issueFor} from './model.mjs';
const $ = id => document.getElementById(id);
let plan = blank(), tab = 'power', pending = null, dirty = false, baseline = null, storageConflict = false;
try { baseline = localStorage.getItem(KEY); if (baseline) plan = validPlan(JSON.parse(baseline)); }
catch { $('notice').textContent = 'Saved plan could not be opened. It was left untouched. Export or inspect browser storage before saving.'; $('save').disabled = true; }
const text = (el,value) => {el.textContent = value;};
function setNotice(message){text($('notice'), message);}
function markDirty(){dirty=true; $('save').textContent='Save changes';}
function conflictNotice(){storageConflict=true;setNotice('Another tab changed this plan. Export your edits, then reload to review the latest saved copy. Save is blocked.');}
window.addEventListener('storage', event=>{if(event.key===KEY && event.newValue!==baseline) conflictNotice();});
function field(label,value,onInput,kind='text'){
  const wrap=document.createElement('label'); wrap.textContent=label;
  const input=document.createElement(kind==='textarea'?'textarea':'input');
  if(kind!=='textarea') input.type=kind;
  input.value=value ?? ''; input.addEventListener('input',()=>{onInput(input.value);markDirty();refreshSummary();});
  wrap.append(input); return wrap;
}
function select(label,options,value,onChange){const wrap=document.createElement('label');wrap.textContent=label;const control=document.createElement('select');for(const option of options){const node=document.createElement('option');node.value=option;node.textContent=option[0].toUpperCase()+option.slice(1);control.append(node);}control.value=value;control.addEventListener('change',()=>{onChange(control.value);markDirty();refreshSummary();});wrap.append(control);return wrap;}
function refreshSummary(){const c=counts(plan.records);text($('total'),c.total);text($('ready'),c.ready);text($('issues'),c.issues);const list=$('issueList');list.replaceChildren();const issues=plan.records.filter(issueFor);if(!issues.length){const p=document.createElement('p');p.textContent='No issues recorded.';list.append(p);}for(const row of issues){const item=document.createElement('div');item.className='issue';const strong=document.createElement('strong');strong.textContent=row.name || 'Unnamed record';const span=document.createElement('span');span.textContent=`${TYPES[row.type].title} · ${issueFor(row)}`;item.append(strong,span);list.append(item);}}
function render(){document.querySelectorAll('[data-tab]').forEach(button=>{if(button.dataset.tab===tab)button.setAttribute('aria-current','page');else button.removeAttribute('aria-current');});text($('sectionTitle'),TYPES[tab].title);text($('sectionHint'),{power:'Circuits, loads and headroom',network:'Devices, addresses and backup paths',cable:'Runs, destinations and field testing'}[tab]);$('add').textContent=`Add ${TYPES[tab].label}`;const host=$('records');host.replaceChildren();const rows=plan.records.filter(row=>row.type===tab);if(!rows.length){const empty=document.createElement('div');empty.className='empty';empty.textContent=`No ${TYPES[tab].title.toLowerCase()} records yet. Add one or import a legacy plan.`;host.append(empty);}for(const row of rows){const card=document.createElement('article');card.className='record';const grid=document.createElement('div');grid.className='fields';grid.append(field(TYPES[tab].label[0].toUpperCase()+TYPES[tab].label.slice(1),row.name,v=>row.name=v),field('Location / zone / path',row.location,v=>row.location=v),select('Status',Array.from(new Set([...TYPES[tab].status,row.status])),row.status,v=>row.status=v),field('Issue / blocker',row.issue,v=>row.issue=v,'textarea'));if(tab==='power'){grid.append(field('Capacity (A)',row.capacity ?? row.sourceRecord?.capacity ?? '',v=>row.capacity=v),field('Draw (A)',row.draw ?? row.sourceRecord?.draw ?? '',v=>row.draw=v));}if(tab==='network'){grid.append(field('IP address',row.ip ?? row.sourceRecord?.ip ?? '',v=>row.ip=v),field('VLAN',row.vlan ?? row.sourceRecord?.vlan ?? '',v=>row.vlan=v));}if(tab==='cable'){grid.append(field('Source',row.source ?? row.sourceRecord?.source ?? '',v=>row.source=v),field('Destination',row.destination ?? row.sourceRecord?.destination ?? '',v=>row.destination=v));}card.append(grid);const foot=document.createElement('div');foot.className='recordFoot';const badge=document.createElement('span');badge.textContent=row.sourceRecord?'Imported copy · original retained':'New record';const remove=document.createElement('button');remove.type='button';remove.textContent='Remove';remove.addEventListener('click',()=>{if(!confirm(`Remove ${row.name || 'this record'} from this plan?`))return;plan.records=plan.records.filter(item=>item.id!==row.id);markDirty();render();});foot.append(badge,remove);card.append(foot);host.append(card);}refreshSummary();}
$('name').value=plan.name;$('name').addEventListener('input',event=>{plan.name=event.target.value;markDirty();});document.querySelectorAll('[data-tab]').forEach(button=>button.addEventListener('click',()=>{tab=button.dataset.tab;render();}));$('add').addEventListener('click',()=>{plan.records.unshift({id:`${tab}-${crypto.randomUUID()}`,type:tab,name:'',location:'',status:'planned',issue:''});markDirty();render();$('records').querySelector('input')?.focus();});
$('save').addEventListener('click',async()=>{
  if(storageConflict){conflictNotice();return;}
  const save=()=>{
    try {
      validPlan(plan);
      if(localStorage.getItem(KEY)!==baseline){conflictNotice();return;}
      const next=JSON.stringify(plan);localStorage.setItem(KEY,next);baseline=next;dirty=false;$('save').textContent='Save';setNotice('Saved on this device. Export a backup for handoff.');
    } catch(error){setNotice(`Save failed: ${error.message}. Your edits are still on screen; export a backup now.`);}
  };
  if(!navigator.locks?.request){setNotice('This browser cannot coordinate saves across tabs. Export a backup and use a browser with Web Locks to save.');return;}
  try {await navigator.locks.request(KEY,{mode:'exclusive'},save);}catch{setNotice('Save lock failed. Export your edits and retry.');}
});
function download(){const blob=new Blob([JSON.stringify(plan,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='infrastructure-plan.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setNotice('Infrastructure plan exported.');}
$('export').addEventListener('click',download);$('import').addEventListener('click',()=>$('file').click());$('file').addEventListener('change',async event=>{const file=event.target.files?.[0];event.target.value='';if(!file)return;try{if(file.size>5_000_000)throw new Error('File is too large');const parsed=JSON.parse(await file.text());if(parsed.schema==='system-by-dave.infrastructure.v1'){pending={full:validPlan(parsed)};text($('previewText'),`Replace the current plan with ${parsed.records.length} records from ${file.name}? Export current work first.`);}else{pending={legacy:legacyPreview(parsed)};text($('previewText'),`Add ${pending.legacy.records.length} ${TYPES[pending.legacy.kind].title.toLowerCase()} records from ${file.name}?`);}$('preview').showModal();}catch(error){pending=null;setNotice(`Import rejected: ${error.message}. Current plan is unchanged.`);}});
$('preview').addEventListener('close',()=>{if($('preview').returnValue!=='confirm'||!pending){pending=null;return;}try{const candidate=validPlan(pending.full || mergeLegacy(plan,pending.legacy));plan=candidate;$('name').value=plan.name;markDirty();render();setNotice('Import added to the unsaved plan. Review, then Save and Export.');}catch(error){setNotice(`Import failed: ${error.message}. Current plan is unchanged.`);}pending=null;});
$('theme').addEventListener('click',()=>{document.body.classList.toggle('light');$('theme').textContent=document.body.classList.contains('light')?'Dark mode':'Light mode';});window.addEventListener('beforeunload',event=>{if(dirty){event.preventDefault();event.returnValue='';}});render();
